package dms

const QPlayAVTransportDesc = `<?xml version="1.0" encoding="utf-8"?>
<scpd xmlns="urn:schemas-upnp-org:service-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <serviceStateTable>
    <stateVariable sendEvents="no">
      <name>TransportState</name>
      <dataType>string</dataType>
      <allowedValueList>
    <allowedValue>STOPPED</allowedValue>
    <allowedValue>PLAYING</allowedValue>
    <allowedValue>PAUSED_PLAYBACK</allowedValue>
    <allowedValue>TRANSITIONING</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>TransportStatus</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentTrack</name>
      <dataType>ui4</dataType>
      <allowedValueRange>
    <minimum>0</minimum>
    <maximum>65535</maximum>
    <step>1</step>
      </allowedValueRange>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentTrackMetaData</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentTrackURI</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>AVTransportURI</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>AVTransportURIMetaData</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>NextAVTransportURI</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>AbsoluteTimePosition</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>RelativeCounterPosition</name>
      <dataType>i4</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>AbsoluteCounterPosition</name>
      <dataType>i4</dataType>
    </stateVariable>
    <stateVariable sendEvents="yes">
      <name>LastChange</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>A_ARG_TYPE_SeekMode</name>
      <dataType>string</dataType>
      <allowedValueList>
    <allowedValue>TRACK_NR</allowedValue>
    <allowedValue>REL_TIME</allowedValue>
    <allowedValue>SECTION</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>A_ARG_TYPE_SeekTarget</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>A_ARG_TYPE_InstanceID</name>
      <dataType>ui4</dataType>
    </stateVariable>
  </serviceStateTable>
  <actionList>
    <action>
      <name>SetAVTransportURI</name>
      <argumentList>
    <argument>
      <name>InstanceID</name>
      <direction>in</direction>
      <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
    </argument>
    <argument>
      <name>CurrentURI</name>
      <direction>in</direction>
      <relatedStateVariable>AVTransportURI</relatedStateVariable>
    </argument>
    <argument>
      <name>CurrentURIMetaData</name>
      <direction>in</direction>
      <relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>
    </argument>
      </argumentList>
    </action>
    <action>
      <name>GetMediaInfo</name>
      <argumentList>
    <argument>
      <name>InstanceID</name>
      <direction>in</direction>
      <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
    </argument>
    <argument>
      <argument>
        <name>CurrentURI</name>
        <direction>out</direction>
        <relatedStateVariable>AVTransportURI</relatedStateVariable>
      </argument>
      <name>CurrentURIMetaData</name>
      <direction>out</direction>
      <relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>
    </argument>
      </argumentList>
    </action>
    <action>
      <name>GetPositionInfo</name>
      <argumentList>
    <argument>
      <name>InstanceID</name>
      <direction>in</direction>
      <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
    </argument>
    <argument>
      <name>Track</name>
      <direction>out</direction>
      <relatedStateVariable>CurrentTrack</relatedStateVariable>
    </argument>
    <argument>
      <name>TrackDuration</name>
      <direction>out</direction>
      <relatedStateVariable>CurrentTrackDuration</relatedStateVariable>
    </argument>
    <argument>
      <name>TrackMetaData</name>
      <direction>out</direction>
      <relatedStateVariable>CurrentTrackMetaData</relatedStateVariable>
    </argument>
    <argument>
      <name>TrackURI</name>
      <direction>out</direction>
      <relatedStateVariable>CurrentTrackURI</relatedStateVariable>
    </argument>
    <argument>
      <name>RelTime</name>
      <direction>out</direction>
      <relatedStateVariable>RelativeTimePosition</relatedStateVariable>
    </argument>
    <argument>
      <name>AbsTime</name>
      <direction>out</direction>
      <relatedStateVariable>AbsoluteTimePosition</relatedStateVariable>
    </argument>
    <argument>
      <name>RelCount</name>
      <direction>out</direction>
      <relatedStateVariable>RelativeCounterPosition</relatedStateVariable>
    </argument>
    <argument>
      <name>AbsCount</name>
      <direction>out</direction>
      <relatedStateVariable>AbsoluteCounterPosition</relatedStateVariable>
    </argument>
      </argumentList>
    </action>
    <action>
      <name>Stop</name>
      <argumentList>
    <argument>
      <name>InstanceID</name>
      <direction>in</direction>
      <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
    </argument>
      </argumentList>
    </action>
    <action>
      <name>Play</name>
      <argumentList>
    <argument>
      <name>InstanceID</name>
      <direction>in</direction>
      <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
    </argument>
    <argument>
      <name>Speed</name>
      <direction>in</direction>
      <relatedStateVariable>TransportPlaySpeed</relatedStateVariable>
    </argument>
      </argumentList>
    </action>
    <action>
      <name>Pause</name>
      <argumentList>
    <argument>
      <name>InstanceID</name>
      <direction>in</direction>
      <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
    </argument>
      </argumentList>
    </action>
    <action>
      <name>Seek</name>
      <argumentList>
    <argument>
      <name>InstanceID</name>
      <direction>in</direction>
      <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
    </argument>
    <argument>
      <name>Unit</name>
      <direction>in</direction>
      <relatedStateVariable>A_ARG_TYPE_SeekMode</relatedStateVariable>
    </argument>
    <argument>
      <name>Target</name>
      <direction>in</direction>
      <relatedStateVariable>A_ARG_TYPE_SeekTarget</relatedStateVariable>
    </argument>
      </argumentList>
    </action>
    <action>
      <name>SetPlayMode</name>
      <argumentList>
    <argument>
      <name>InstanceID</name>
      <direction>in</direction>
      <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
    </argument>
    <argument>
      <name>NewPlayMode</name>
      <direction>in</direction>
      <relatedStateVariable>CurrentPlayMode</relatedStateVariable>
    </argument>
      </argumentList>
    </action>
  </actionList>
</scpd>`

